package com.nexus.simplify.database.tasktype;

import javafx.beans.property.*;

import org.joda.time.DateTime;
import org.joda.time.format.*;

/**
 * Represents an instance of a task without due date or start and end time.
 * @author Tan Qian Yi
 * */
public class GenericTask {
	
	/**
	 * Default value of workload when user does not specify is 1.
	 * */
	private static final int DEFAULT_WORKLOAD_VALUE = 1;
	private static final String ID_FORMAT = "ddMMyyHHmmss";
	
	//------------------//
	// Class Attributes //
	//------------------//
	
	private final StringProperty id;
	private final StringProperty name;
	private final IntegerProperty workload;
	
	//--------------//
	// Constructors //
	//--------------//
	
	/**
	 * Constructor without workload.
	 * 
	 * @param name name of task
	 * @param  
	 * */
	public GenericTask(String name) {
		this.name = new SimpleStringProperty(name);
		this.workload = new SimpleIntegerProperty(DEFAULT_WORKLOAD_VALUE);
		this.id = new SimpleStringProperty(generateId());
	}

	/**
	 * Constructor with workload.
	 * 
	 * @param name name of task
	 * @param workload amount of effort required to do the task ranging from 1 to 5
	 * */
	public GenericTask(String name, int workload) {
		this.name = new SimpleStringProperty(name);
		this.workload = new SimpleIntegerProperty(workload);
		this.id = new SimpleStringProperty(generateId());
	}
	
	/**
	 * Constructor with workload and id.
	 * 
	 * @param name name of task in StringProperty
	 * @param workload amount of effort required to do the task ranging from 1 to 5 in IntegerProperty
	 * @param id id of task in StringProperty
	 * */
	public GenericTask(StringProperty name, IntegerProperty workload, StringProperty id) {
		this.name = name;
		this.workload = workload;
		this.id = id;
	}
	
	//--------------------//
	// Attribute Mutators //
	//--------------------//
	
	/**
	 * Id is generated by task creation time and used to sort task lists by default.
	 * */
	private static String generateId() {
		DateTime currentTime = new DateTime();
		DateTimeFormatter format = DateTimeFormat.forPattern(ID_FORMAT);
		return format.print(currentTime);
	}
	
	/**
	 * Default setter for class attribute id.
	 * 
	 * @param id the new id for the task
	 * */
	public void setId(String id) {
		this.id.set(id);
	}
	
	/**
	 * Default setter for class attribute name.
	 * 
	 * @param name the new name for the task
	 * */
	public void setName(String name) {
		this.name.set(name);
	}
	
	/**
	 * Default setter for class attribute workload.
	 * 
	 * @param workload the new workload for the task
	 * */
	public void setWorkload(int workload) {
		this.workload.set(workload);
	}
	
	//---------------------//
	// Attribute Accessors //
	//---------------------//
	
	/**
	 * Default getter method for attribute id.
	 * 
	 * @return id of task
	 * */
	public String getId() {
		return id.get();
	}
	
	/**
	 * Default getter method for attribute name.
	 * 
	 * @return name of task
	 * */
	public String getName() {
		return name.get();
	}
	
	/**
	 * Default getter method for attribute workload.
	 * 
	 * @return workload of task
	 * */
	public int getWorkload() {
		return workload.get();
	}
	
	/**
	 * Returns the id of the task formatted as a StringProperty Object.
	 * 
	 * @return id of task as StringProperty Object
	 * @author tohjianfeng
	 * */
	public StringProperty getIDAsStringProperty() {
		return id;
	}
	
	/**
	 * Returns the ID of the task in DateTime.
	 * 
	 * @return ID of task as DateTime
	 * */
	public DateTime getIDAsDT() {
		DateTimeFormatter format = DateTimeFormat.forPattern(ID_FORMAT);
		DateTime ID = format.parseDateTime(id.get());
		return ID;
	}
	
	/**
	 * Returns the name of the task formatted as a StringProperty Object.
	 * 
	 * @return name of task as StringProperty Object
	 * */
	public StringProperty getNameAsStringProperty() {
		return name;
	}
	
	/**
	 * Returns the workload of the task formatted as a IntegerProperty Object.
	 * 
	 * @return workload of task as IntegerProperty Object
	 * */
	public IntegerProperty getWorkloadAsIntegerProperty() {
		return workload;
	}
	
	/**
	 * Returns an exact copy of the task.
	 * */
	public GenericTask getCopy() {
		StringProperty cName = new SimpleStringProperty(getName());
		IntegerProperty cWorkload = new SimpleIntegerProperty(getWorkload());
		StringProperty cID = new SimpleStringProperty(getId());
		GenericTask copy = new GenericTask(cName, cWorkload, cID);
		return copy;
	}
}
